# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 1.0
default_acceleration_scaling_factor: 1.0

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  drive_joint:
    has_velocity_limits: false
    max_velocity: 0.0
    has_acceleration_limits: false
    max_acceleration: 1
  joint1:
    has_velocity_limits: true
    max_velocity: 4.36332313
    has_acceleration_limits: true
    max_acceleration: 4.36332313
  joint2:
    has_velocity_limits: true
    max_velocity: 4.36332313
    has_acceleration_limits: false
    max_acceleration: 4.36332313
  joint3:
    has_velocity_limits: true
    max_velocity: 4.36332313
    has_acceleration_limits: true
    max_acceleration: 4.36332313
  joint4:
    has_velocity_limits: true
    max_velocity: 5.5850536064
    has_acceleration_limits: true
    max_acceleration: 5.5850536064
  joint5:
    has_velocity_limits: true
    max_velocity: 5.5850536064
    has_acceleration_limits: true
    max_acceleration: 5.5850536064
  joint6:
    has_velocity_limits: true
    max_velocity: 7.3303828584
    has_acceleration_limits: true
    max_acceleration: 7.3303828584
